ardriveapp/ardrive-cli

src/index.ts, src/prompts.ts
There is a natural delay between price estimation and when the total AR taken from the user's wallet. This estimation can be improved in core-js, but when uploading many larger files the delay becomes larger and a volatile AR price could be much different in 10-15 minutes when a large transaction has settled.
This PR simply clarifies that the prompt is an estimation, rather than the total that will be charged.
=> PE-50: Describe price calculation as estimation rather than total

package.json
This PR locks the CLI to `ardrive-core-js` version `0.4.0` and increments CLI version to `0.3.0` in preparation for releasing Core/CLI as npm packages
=> chore(version): Use core version `0.4.0` PE-95

package.json
This PR adjusts the `yarn start` command to use `tsc -w`, which will rebuild the `lib` output on each save.
=> chore(dev-reload): Add tsc watch command to reload dev env PE-204

src/CLICommand/cli_command.ts, src/ardrive.ts, src/arfs_trx_data_types.ts, src/arfsdao.ts, src/commands/create_drive.ts, src/commands/drive_info.ts, src/commands/send_ar.ts, src/commands/upload_file.ts, src/index.ts, src/parameter_declarations.ts, src/types.ts, src/utils.ts, src/wallet_new.ts
Adds precise fee estimation to all existing writing commands and the ability to boost miner rewards by a multiple for all commands that send transactions. NOTE: the merge destination branch of `cli_v2_smartweave`. We'll want to merge to the `cli_v2` branch once the former has been merged there.
=> PE-448: fee boost

src/ardrive.ts, src/arfs_trx_data_types.ts, src/arfsdao.ts, src/commands/create_drive.ts, src/commands/drive_info.ts, src/commands/folder_info.ts, src/commands/list_folder.ts, src/commands/upload_file.ts
This PR applies the driveKey changes to every command and removes all instances of password and drivePassword in the ArDrive and ArFSDao layers. The commands seem to be working again.
=> Cli v2 use drive key everywhere else

.husky/pre-commit
This PR adds a typecheck command to the husky hook. There seems to be a `tsc-files` command being used in the `lint-staged` command, but that isn't actually preventing a commit properly.
Adding this `yarn typecheck` to the husky hook correctly typechecks locally and will reject non-compliant code. This will prevent a dev from pushing code that will not compile locally rather than failing the CI check.
Notably, I did not add the yarn test command to the hook. It currently takes ~30 seconds to completely test the codebase. Thats a little to long for me, at least on smaller commits. (Edit: ~30 seconds estimate is on a downstream branch that includes testing the seed-phrase code, not currently on the `cli_v2` branch)
I think that we should typecheck, lint, and format locally on before every …
=> chore(husky): Add typecheck to husky hook

src/commands/create_folder.ts
This PR correctly passes down the required parent folder ID to the create folder methods.
=> fix(create folder): Pass parent folder ID PE-319

src/ardrive.ts
This PR fixes a naming error on private bulk uploads. Each parent folder was mistakenly naming its child folder.
=> fix(bulk priv upload): Use correct folder base path as name PE-541

src/CLICommand/parameters_helper.ts, src/arfsdao.ts, src/arfsdao_anonymous.ts, src/commands/list_drive.ts, src/folderHierarchy.ts
We might want to use bigint in the future. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
For now let's limit us to MAX_SAFE_INTEGER
=> PE-518: use MAX_SAFE_INTEGER instead of POSITIVE_INFINITY

package.json, tests/integration/ardrive.int.test.ts, tsconfig.json, tsconfig.prod.json
This PR adds a prod version of the `tsconfig` file that excludes the test files and allows the dev environment compiler to type-check the tests directory
=> chore(tsconfig): Allow dev env typecheck in test files PE-581

src/ardrive.ts, src/arfs_file_wrapper.ts, src/arfsdao.ts, src/utils/filter_methods.ts, src/utils/stubs.ts, tests/integration/ardrive.int.test.ts
This PR enforces unique file names within the supplied destination folder for `upload-file` and `move-file`.
- Errors out if destination folder has conflicting FILE or FOLDER name
- Errors out if destination folder has conflicting FOLDER name
- Uploads as a REVISION if destination folder has conflicting FILE name
- Folder names that conflict with a destination FILE name will error
- Folder names that conflict with destination FOLDER name will use the existing folder ID rather than creating a new folder
- File names that conflict with a destination FOLDER name will error
- File names that conflict with destination FILE name will be uploaded as a REVISION
=> PE-558: Enforce unique file name

src/ardrive.ts, src/arfsdao.ts, src/arfsdao_anonymous.ts
This PR passes the derived drive owner down into the list methods, which will filter the `list-drive` and `list-folder` commands by the original drive owner.
Fixes #124
=> fix(owner filter): Pass owner down through list methods PE-645

README.md, src/CLICommand/parameters_helper.ts, src/ardrive.ts, src/arfs_file_wrapper.ts, src/arfsdao.ts, src/parameter_declarations.ts, src/utils/mapper_functions.ts, tests/integration/ardrive.int.test.ts
This PR adds the `--upsert` parameter which will become the new default on single and bulk file uploads. 
On a FILE to FILE name conflict within the destination folder, the upsert option will compare `lastModifiedDate` on the files. If they match, the upload will be skipped. Otherwise a new REVISION will be created.
=> PE-633: Uploads will "upsert" by default

src/ardrive.ts, src/arfsdao_anonymous.ts, src/commands/move_file.ts, src/commands/move_folder.ts, src/commands/tx_status.ts, src/utils/arfs_builders/arfs_folder_builders.ts, tests/integration/ardrive.int.test.ts
•Needed to make sure destructured options variables got fed to type-safe constructors before use with ArDrive class.
• Needed to replace all usages of .includes on arrays of objects to use .some instead.
=> PE-635 Bug Fixes

README.md
Link was broken and I believe the new link is correct.
=> Updated ArFS Link

package.json, src/ardrive.ts, src/commands/send_ar.ts, src/utils/ardrive.test.ts
This PR changes the tip transaction tags to be consistent with the web app.
Fixes #136
=> PE-675: Use consistent tags on tip transactions

package.json, src/ardrive.ts, src/arfsdao.ts, src/arfsdao_anonymous.ts, tests/integration/ardrive.int.test.ts
This PR asserts the drive privacy of a folder creation during the GQL call to derive the drive owner.
As this is a hotfix, the version has been bumped here and the target branch is `master`. Proposed GitHub release notes:
- Creating private entities inside public drives and public entities inside private drives will now cause an error
- Creating private entities with the wrong drive key or password will now cause an error
=> fix(create folder): Assert drive privacy during folder creation PE-679

src/utils/local_file_path.test.ts, src/utils/local_file_path.ts
Adds missing tests for the `getOutputFilePathAndName` function.
Also fixes the broken test on which the `switch..case` caught the exception I was throwing
=> test(download file): implement unit tests PE-464

package.json, yarn.lock
This PR locks the arweave version to 1.10.18. We encounted an error on the transaction.getData method
=> fix(arweave version): Lock arweave version to avoid getData 1.10.19 error PE-845

src/commands/download_folder.ts, src/commands/upload_file.ts, src/parameter_declarations.ts
Simplifies the parameter aliases for paths:
- `--local-file-path` and `--dest-folder-path` are consolidated to `--local-path`
- `--local-files` is renamed to `--local-paths-csv`
Still pending: the `--local-paths` parameter at https://github.com/karlprieb/ardrive-cli/pull/1
=> PE-781: consolidate flag aliases

bats_test/upload-file/single-bundled-files.bats
This PR adds the ArDrive community tip to the bundle transaction or the data transaction during v2 uploads by applying the changes from this [Core PR](https://github.com/ardriveapp/ardrive-core-js/pull/115).
=> PE-636: Send community tip with the data tx or bundle tx

src/CLICommand/parameters_helper.test.ts
This PR should make false build failures from the unpredictably long seed phrase test more infrequent
=> test(seed phrase): Double timeout to deter false build failures PE-1005

bats_test/downloads/drive-downloads/happy_paths.bats
It was a failing BATS test before the release (#261). We figured out that the command would work as expected when running by hand. The day after (today) I ran the test again and it seem to pass as expected.
My conclusion is that there was some condition at the docker environment in that specific instance I had as we weren't able to reproduce in a fresh one.
=> PE-1066: Failing BATS for download-drive

src/CLICommand/cli_command.test.ts, src/CLICommand/parameters_helper.test.ts
Changes
- Adds a unit tests to ensure --add-ipfs-flag and --private are disallowed in conjunction
=> test(ipfs): adds a test for ipfs with private entities PE-1987
